# Generated by Django 3.2.13 on 2022-07-02 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(choices=[('1º', '1º ano'), ('2º', '2º ano'), ('3º', '3º ano'), ('4º', '4º ano'), ('5º', '5º ano'), ('6º', '6º ano'), ('7º', '7º ano'), ('8º', '8º ano'), ('9º', '9º ano')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BaseCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseCurricular', models.CharField(choices=[('Linguagens', 'Linguagens'), ('Matemática', 'Matemática'), ('Ciências da Natureza', 'Ciências da Natureza'), ('Ciências Humanas', 'Ciências Humanas')], max_length=340, verbose_name='baseCurricular')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=80, verbose_name='email')),
                ('instagram', models.CharField(max_length=50, verbose_name='Instagram')),
                ('twitter', models.CharField(max_length=50, verbose_name='Twitter')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatssApp')),
                ('youtube', models.CharField(max_length=30, verbose_name='Youtube')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=150, verbose_name='Disciplina')),
                ('ano', models.CharField(max_length=20, verbose_name='Ano')),
                ('conteudo', models.TextField(max_length=500, verbose_name='Conteúdos')),
                ('objetivos', models.TextField(max_length=500, verbose_name='Objetivos')),
                ('experimentosRoboticos', models.TextField(max_length=200, verbose_name='Protótipos Robóticos vinculados')),
            ],
        ),
        migrations.CreateModel(
            name='EtapasEnsino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapasEnsin', models.CharField(max_length=100, verbose_name='etapasEnsin')),
            ],
        ),
        migrations.CreateModel(
            name='NomePortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePortfolio', models.CharField(max_length=300, verbose_name='nomePortfolio')),
            ],
        ),
        migrations.CreateModel(
            name='NomePrototipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePrototipo', models.CharField(max_length=300, verbose_name='nomePrototipo')),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataformaPrototip', models.CharField(max_length=200, verbose_name='plataformaPrototip')),
            ],
        ),
        migrations.CreateModel(
            name='Protototipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Humanas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeSubItemHumanas', models.CharField(choices=[('Geografia', 'Geografia'), ('História', 'História'), ('Ensino religioso', 'Ensino religioso')], max_length=50, verbose_name='nomeSubItemHumanas')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Linguagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeSubItemLinguagem', models.CharField(choices=[('Lingua Portuguesa', 'Lingua Portuguesa'), ('Artes Visuais', 'Artes Visuais'), ('Teatro', 'Teatro'), ('Dança', 'Dança'), ('Música', 'Música'), ('Educação Física', 'Educação Física'), ('Língua Estrangeira', 'Língua Estrangeira')], max_length=50, verbose_name='nomeSubItemLinguagem')),
            ],
        ),
        migrations.CreateModel(
            name='TematicasLinguagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tematicasLinguagens', models.CharField(max_length=200, verbose_name='tematicasLinguagens')),
            ],
        ),
        migrations.CreateModel(
            name='TematicasMatematica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tematicasMatematica', models.CharField(max_length=200, verbose_name='tematicasMatematica')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuitoPrototipo', models.TextField(max_length=300, verbose_name='circuitoPrototipo')),
                ('sourceCodePrototipos', models.TextField(max_length=300, verbose_name='sourceCodePrototipos')),
                ('materiaisPrototipos', models.TextField(max_length=300, verbose_name='materiaisPrototipos')),
                ('creditosReferencia', models.CharField(max_length=200, verbose_name='creditosReferencia')),
                ('creditosAdaptacaoPedagogica', models.CharField(max_length=200, verbose_name='creditosAdaptacaoPedagogica')),
                ('siteReferencia', models.CharField(max_length=200, verbose_name='siteReferencia')),
                ('canalAudioVisual', models.CharField(max_length=200, verbose_name='canalAudioVisual')),
                ('etapasEnsino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etapasensino')),
                ('nomePortfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nomeportfolio')),
                ('plataformaPrototipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plataforma')),
                ('tematicaLing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tematicaslinguagem')),
                ('tematicaMat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tematicasmatematica')),
            ],
        ),
        migrations.CreateModel(
            name='Conteudos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=1, verbose_name='area')),
                ('conteudo', models.TextField(max_length=400, verbose_name='Conteúdo')),
                ('ano', models.ForeignKey(choices=[('1º', '1º ano'), ('2º', '2º ano'), ('3º', '3º ano'), ('4º', '4º ano'), ('5º', '5º ano'), ('6º', '6º ano'), ('7º', '7º ano'), ('8º', '8º ano'), ('9º', '9º ano')], max_length=10, on_delete=django.db.models.deletion.CASCADE, to='core.ano')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoMatematica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudoMat', models.TextField(max_length=300, verbose_name='conteudoMat')),
                ('objetivosMat', models.TextField(max_length=300, verbose_name='objetivosMat')),
                ('habilidadesMatBncc', models.TextField(max_length=300, verbose_name='habilidadesMatBncc')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ano')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.portfolio')),
                ('tematicaMat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tematicasmatematica')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoLinguagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudoLing', models.TextField(max_length=300, verbose_name='conteudoLing')),
                ('objetivosLing', models.TextField(max_length=300, verbose_name='objetivosLing')),
                ('habilidadesLingBncc', models.TextField(max_length=300, verbose_name='habilidadesLingBncc')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ano')),
                ('linguagens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sub_linguagem')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.portfolio')),
                ('tematicaLing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tematicaslinguagem')),
            ],
        ),
    ]
